[package]
name = "rusty_grad"
version = "0.2.0"
authors = ["sami jaghouar <sami.jaghouar@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.3"
